### ISSUE TITLE
Not cloning in IDE browser

### ISSUE THREAD

**Issue by AimanAlmureish** [learn-co-curriculum/fewpjs-adding-behavior-with-methods#11]

**Comment by gzavaglia** [comment]
Yup, same thing here

**Comment by AimanAlmureish** [comment]
Thank you so much for replying and wishing you all the best! Sent from Mail for Windows 10 From: Giovana ZavagliaSent: Saturday, November 30, 2019 12:07 AMTo: learn-co-curriculum/fewpjs-adding-behavior-with-methodsCc: Aiman Almureish; AuthorSubject: Re: [learn-co-curriculum/fewpjs-adding-behavior-with-methods] Not cloning in IDE browser (#11) Yup, same thing here—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by carl1984r** [comment]
Same issue.

// ♥ learn open fewpjs-adding-behavior-with-methods-online-web-sp-000
Looking for lesson...
Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/bin/learn-open:7:in `<to
p (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb
:12:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb
:38:in `run'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `classify'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `find'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `each'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:20:in `block in classify'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in
 `detect': undefined method `any?' for false:FalseClass (NoMethodError)

**Comment by marsbhoward** [comment]
has anyone figured out  any fixes for this?

**Comment by gzavaglia** [comment]
I haven't figure out a fix, however you can just go into the github lab ( [https://github.com/learn-co-curriculum/fewpjs-adding-behavior-with-methods](url)) and clone it.

The tests work so you can test your code, the only thing is I can't "submit" it.

**Comment by AimanAlmureish** [comment]
Try to make a pull request then compare your work! I think this will work! Good luck!

**Comment by AimanAlmureish** [comment]
> 
> 
> has anyone figured out any fixes for this?

Make a pull request and compare repos! It should work after you have done all tests!

**Comment by rrcobb** [comment]
Thanks all for reporting this issue! It looks like it was a problem with the `.learn` file in this repo. It should be fixed by 0f58aaf. 

If anyone is still running into this problem, please reopen this issue!
